# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-03 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='phome',
            new_name='phone',
        ),
    ]
